#!/usr/bin/env python3
"""
SID SUPERSTATION - Frequency Table Generator
Generates 16-bit frequency values for the SID chip for all MIDI notes (0-95)

The SID chip uses a 16-bit frequency register that determines the oscillator frequency.
The formula is: frequency_value = (note_frequency * 16777216) / clock_frequency

For PAL C64: clock_frequency = 985248 Hz
For NTSC C64: clock_frequency = 1022727 Hz

This generates PAL values by default.
"""

import math

def note_to_frequency(note_number):
    """Convert MIDI note number to frequency in Hz"""
    # MIDI note 0 = C-1 = 8.176 Hz
    # A4 (MIDI note 69) = 440 Hz
    return 440.0 * math.pow(2.0, (note_number - 69) / 12.0)

def frequency_to_sid_value(freq_hz, clock_hz=985248):
    """Convert frequency in Hz to SID 16-bit frequency value"""
    # SID frequency formula: freq_value = (freq_hz * 16777216) / clock_hz
    return int((freq_hz * 16777216) / clock_hz)

def generate_frequency_table():
    """Generate frequency table for MIDI notes 0-95 (8 octaves)"""
    print("// ============================================================================")
    print("// SID SUPERSTATION - Frequency Table Data")
    print("// Generated by freq_calc.py")
    print("// ============================================================================")
    print("// 16-bit frequency values for MIDI notes 0-95 (C-0 to B-7)")
    print("// PAL clock: 985248 Hz")
    print("// ============================================================================")
    print()
    print("freq_table_lo:")
    
    # Generate low bytes
    for octave in range(8):
        values = []
        for note in range(12):
            midi_note = octave * 12 + note
            if midi_note <= 95:
                freq_hz = note_to_frequency(midi_note)
                sid_value = frequency_to_sid_value(freq_hz)
                low_byte = sid_value & 0xFF
                values.append(low_byte)
        
        # Print as data bytes
        if values:
            data_str = ", ".join([f"${v:02X}" for v in values])
            print(f"    .byte {data_str}  // Octave {octave}")
    
    print()
    print("freq_table_hi:")
    
    # Generate high bytes
    for octave in range(8):
        values = []
        for note in range(12):
            midi_note = octave * 12 + note
            if midi_note <= 95:
                freq_hz = note_to_frequency(midi_note)
                sid_value = frequency_to_sid_value(freq_hz)
                high_byte = (sid_value >> 8) & 0xFF
                values.append(high_byte)
        
        # Print as data bytes
        if values:
            data_str = ", ".join([f"${v:02X}" for v in values])
            print(f"    .byte {data_str}  // Octave {octave}")
    
    print()
    print("// Note name reference:")
    print("// 0=C, 1=C#, 2=D, 3=D#, 4=E, 5=F, 6=F#, 7=G, 8=G#, 9=A, 10=A#, 11=B")

if __name__ == "__main__":
    generate_frequency_table()
