// ============================================================================
// SID SUPERSTATION - Lookup Tables
// ============================================================================
// Contains frequency tables and LFO waveform tables
// ============================================================================

// ============================================================================
// Frequency Table (Generated by freq_calc.py)
// 16-bit frequency values for MIDI notes 0-95 (C-0 to B-7)
// PAL clock: 985248 Hz
// ============================================================================

freq_table_lo:
    .byte $8B, $93, $9C, $A5, $AF, $B9, $C4, $D0, $DC, $EA, $F8, $06  // Octave 0
    .byte $16, $26, $38, $4B, $5E, $73, $89, $A1, $B9, $D4, $F0, $0D  // Octave 1
    .byte $2C, $4D, $71, $96, $BD, $E7, $13, $42, $73, $A8, $E0, $1B  // Octave 2
    .byte $59, $9B, $E2, $2C, $7B, $CE, $27, $84, $E7, $51, $C0, $36  // Octave 3
    .byte $B3, $37, $C4, $59, $F6, $9D, $4E, $09, $CF, $A2, $81, $6D  // Octave 4
    .byte $67, $6F, $88, $B2, $ED, $3A, $9C, $13, $9F, $44, $02, $DA  // Octave 5
    .byte $CE, $DF, $11, $64, $DA, $75, $38, $26, $3F, $89, $04, $B4  // Octave 6
    .byte $9C, $BF, $22, $C8, $B4, $EB, $71, $4C, $7F, $12, $08, $68  // Octave 7

freq_table_hi:
    .byte $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $01  // Octave 0
    .byte $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $02  // Octave 1
    .byte $02, $02, $02, $02, $02, $02, $03, $03, $03, $03, $03, $04  // Octave 2
    .byte $04, $04, $04, $05, $05, $05, $06, $06, $06, $07, $07, $08  // Octave 3
    .byte $08, $09, $09, $0A, $0A, $0B, $0C, $0D, $0D, $0E, $0F, $10  // Octave 4
    .byte $11, $12, $13, $14, $15, $17, $18, $1A, $1B, $1D, $1F, $20  // Octave 5
    .byte $22, $24, $27, $29, $2B, $2E, $31, $34, $37, $3A, $3E, $41  // Octave 6
    .byte $45, $49, $4E, $52, $57, $5C, $62, $68, $6E, $75, $7C, $83  // Octave 7

// Note name reference:
// 0=C, 1=C#, 2=D, 3=D#, 4=E, 5=F, 6=F#, 7=G, 8=G#, 9=A, 10=A#, 11=B

// ============================================================================
// LFO Waveform Tables (256 bytes each)
// ============================================================================

// Triangle wave (0 → 255 → 0)
lfo_triangle:
    .fill 128, i * 2         // Rising edge: 0, 2, 4, ... 254
    .fill 128, 255 - (i * 2) // Falling edge: 255, 253, 251, ... 1

// Sawtooth wave (0 → 255, reset)
lfo_sawtooth:
    .fill 256, i             // Linear ramp: 0, 1, 2, ... 255

// Square wave (0/255 toggle)
lfo_square:
    .fill 128, 0             // Low half
    .fill 128, 255           // High half

// Sine wave (approximation using lookup table)
lfo_sine:
    .fill 256, round(127.5 + 127.5 * sin(toRadians(i * 360.0 / 256.0)))

// Random/Sample & Hold (pre-generated random values)
lfo_random:
    .fill 256, floor(random() * 256)

// ============================================================================
// Note Name Table (for UI display)
// ============================================================================
note_names:
    .text "C-C#D-D#E-F-"
    .text "F#G-G#A-A#B-"

// ============================================================================
// ADSR Time Tables (approximate milliseconds)
// ============================================================================
// Attack/Decay/Release rates in milliseconds for ADSR values 0-15
adsr_time_table:
    .word 2, 8, 16, 24, 38, 56, 68, 80
    .word 100, 250, 500, 800, 1000, 3000, 5000, 8000
